name: helen_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/farmers/white-helen.png
    - images/farmers/login-bg.jpg
    - images/farmers/logo-opa.png
    - images/farmers/clouds.png
    - images/farmers/addproduct.png
    - images/farmers/order.png
    - images/farmers/aichat.png
    - images/farmers/upcomingevents.png
    - images/farmers/lemon.png
    - images/farmers/carrots.png
    - images/farmers/sample-event.png
    - images/are-you-a-farmer.png
    - images/are-you-a-buyer.png
    - images/farmers/farmer-profile.png
    - images/buyers/buyer-login-bg.jpg
    - images/farmers/dummyproductlist.png
    - images/buyers/Carrot.png
    - images/buyers/Corn.png
    - images/buyers/Lemon.png
    - images/buyers/Tomatoes.png
    - images/buyers/product-corn.png
    - images/buyers/checkout-pic.png
    - images/buyers/sample-buyer-pic.jpg
    - images/farmers/lucbantradingpost.jpg
    - images/farmers/Frame 5.png
    
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
